/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Dokter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;
import java.rmi.registry.Registry;
import java.rmi.NotBoundException;
import java.rmi.registry.LocateRegistry;
import java.rmi.RemoteException;
import java.rmi.MarshalException;
import database.Service.Detail_Resep_Service;
import database.Service.Obat_Service;
import database.entity.detail_lihat_resep;
import java.awt.Color;
import java.util.List;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;


/**
 *
 * @author tinot
 */
public class Form_Tambah_Resep extends javax.swing.JFrame {
    private Detail_Resep_Service service3;
    private Obat_Service service4;
    private Panel_Resep pp;
    private detail_lihat_resep lr;
    Registry registry;
    /**
     * Creates new form resepObat
     */
    public Form_Tambah_Resep(Panel_Resep pp) throws RemoteException, NotBoundException {
        initComponents();
        registry = LocateRegistry.getRegistry("0.0.0.0", 9750);
        service3 = (Detail_Resep_Service) registry.lookup("service3");        
        service4 = (Obat_Service) registry.lookup("service4");
        this.pp = pp;
        namaObat.setVisible(false);
        jml.setVisible(false);
    }

    private void refresh(){
        kodeObat.setText("Masukkan kode obat");
        namaObat.removeAllItems();
        namaObat.setVisible(false);
        jml.removeAll();
        jml.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kodeObat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        namaObat = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jml = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(700, 450));

        jLabel1.setText("Kode Obat       :");

        kodeObat.setText("Masukkan Kode Obat");
        kodeObat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                kodeObatFocusGained(evt);
            }
        });

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama Obat      :");

        namaObat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Obat" }));

        jLabel4.setText("Jumlah             :");

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Form Tambah Obat");

        jButton3.setText("Kembali");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jml, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(namaObat, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(kodeObat, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kodeObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kodeObatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kodeObatFocusGained
        kodeObat.setText("");
    }//GEN-LAST:event_kodeObatFocusGained

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//        Panel_Rekam_Medik_Tambah a = new Panel_Rekam_Medik_Tambah();
//        a.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nama = "";
        String hasil = "";
        
        if(namaObat.getSelectedItem().equals("Pilih Obat")||jml.getValue().equals(null)){
            JOptionPane.showMessageDialog(null, "Data Yang Anda Inputkan Belum Lengkap");

        }
        else{
            lr = new detail_lihat_resep();
            lr.setObat(namaObat.getSelectedItem().toString());
            lr.setQty(Integer.parseInt(String.valueOf(jml.getValue())));
            pp.list.add(lr);
//            String ID = null;
//            
//            try {
//                ID = "RES"+service3.getResep().size();
//                nama = String.valueOf(namaObat.getSelectedItem()).toString();
//                //hasil = service4.getIdObat(nama);
//            } catch (RemoteException ex) {
//                Logger.getLogger(Form_Tambah_Resep.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            try {
//               detail_resep_obat resep = new detail_resep_obat();
//               resep.setid_detail_resep(ID);
//               resep.setid_rekam_medis("rk01");     //perlu DIGANTI !!!!
//               resep.setid_obat(hasil);
//               resep.setqty_detail_resep(Integer.parseInt(String.valueOf(jml.getValue())));
//               
//                if(service3.insertResep(resep)!=null){
//                    
//                    int opsi = JOptionPane.showConfirmDialog(null, "Data Anda berhasil disimpan. Apakah Anda akan menambahkan data lagi?","", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
//                    if(opsi==0){
//                        refresh();
//                    }
////                    else{
////                        Panel_Rekam_Medik_Tambah a = new Panel_Rekam_Medik_Tambah();
////                        a.setVisible(true);
////                        this.dispose();
////                    }
//                }
//                else{
//                    JOptionPane.showMessageDialog(null, "Input Data Eror", "PESAN", JOptionPane.ERROR_MESSAGE);
//                }
//                
//                
//            }
//            catch(RemoteException exception){
//                exception.printStackTrace();
//            }
////            Panel_Rekam_Medik_Tambah a = new Panel_Rekam_Medik_Tambah();
////            a.setVisible(true);
////            this.dispose();
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        namaObat.setVisible(true);
        jml.setVisible(true);
        String kode = kodeObat.getText();
//        try {
//     //       List a = service4.getObatList(kode);
////            for (int i = 0; i < a.size(); i++) {
////                namaObat.addItem(a.get(i).toString());
//            }
//        } catch (RemoteException ex) {
//            Logger.getLogger(Form_Tambah_Resep.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jml;
    private javax.swing.JTextField kodeObat;
    private javax.swing.JComboBox namaObat;
    // End of variables declaration//GEN-END:variables
}
