/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Dokter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;
import java.rmi.registry.Registry;
import java.rmi.NotBoundException;
import java.rmi.registry.LocateRegistry;
import java.rmi.RemoteException;
import java.rmi.MarshalException;
import database.Service.Detail_Resep_Service;
import database.Service.Obat_Service;
import database.entity.detail_lihat_resep;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.text.JTextComponent;


/**
 *
 * @author tinot
 */
public class Form_Tambah_Resep extends javax.swing.JFrame {
    private Detail_Resep_Service service3;
    private Obat_Service service4;
    private Panel_Resep pp;
    private detail_lihat_resep lr;
    Registry registry;
    /**
     * Creates new form resepObat
     */
    public Form_Tambah_Resep(Panel_Resep pp) throws RemoteException, NotBoundException {
        initComponents();
        service3 = pp.gui.drs;       
        service4 = pp.gui.ob;
        this.pp = pp;
        jml.setVisible(true);
        
        boxNamaObat.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent evt){
                String keyWord = boxNamaObat.getEditor().getItem().toString();
                if (evt.getKeyCode()>=65 && evt.getKeyCode()<=90 || evt.getKeyCode()>=96 && evt.getKeyCode()<=105 || evt.getKeyCode()==8) {
                    boxNamaObat.setModel(getListObat(keyWord));
                    if (boxNamaObat.getItemCount()>0) {
                        boxNamaObat.showPopup();
                        if (evt.getKeyCode()!=8) {
                            ((JTextComponent)boxNamaObat.getEditor().getEditorComponent()).select(keyWord.length(), boxNamaObat.getEditor().getItem().toString().length());
                        }
                        else{
                            boxNamaObat.getEditor().setItem(keyWord);
                        }
                    }
                    else{
                        boxNamaObat.addItem(keyWord);
                    }
                }
            
            }
        
        });
    }

    private void refresh(){
        jml.removeAll();
        jml.setVisible(true);
    }
    
    public DefaultComboBoxModel getListObat(String kataKunci){
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        try {
            List a = service4.getObatList(kataKunci);
            for (int i = 0; i < a.size(); i++) {
                model.addElement(a.get(i).toString());
            }
        } catch (RemoteException ex) {
            Logger.getLogger(Form_Tambah_Resep.class.getName()).log(Level.SEVERE, null, ex);
        }
        return model;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jml = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        boxNamaObat = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(700, 450));

        jLabel2.setText("Nama Obat      :");

        jLabel4.setText("Jumlah             :");

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Form Tambah Obat");

        jButton3.setText("Kembali");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        boxNamaObat.setEditable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Masukkan nama obat");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jml, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxNamaObat, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(boxNamaObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        pp.gui.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nama = "";
        String hasil = "";
        
        if(boxNamaObat.getEditor().getItem().toString().equals("") ||jml.getValue().equals(null)){
            JOptionPane.showMessageDialog(null, "Data Yang Anda Inputkan Belum Lengkap");

        }
        else{
            lr = new detail_lihat_resep();
            try {
                lr.setIdObat(service4.getIdObat(boxNamaObat.getEditor().getItem().toString()));
                lr.setObat(boxNamaObat.getEditor().getItem().toString());
                lr.setQty(Integer.parseInt(String.valueOf(jml.getValue())));
                pp.list.add(lr);
                pp.updateTable(pp.list);
                this.dispose();
            } catch (RemoteException ex) {
                Logger.getLogger(Form_Tambah_Resep.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
//            pp.list.add(lr);
//            pp.listResep.add(lr.getObat());
//            pp.nama = namaObat.getSelectedItem().toString();
//            pp.updateResep();
//            pp.gui.setVisible(true);
//            String ID = null;
//            
//            try {
//                ID = "RES"+service3.getResep().size();
//                nama = String.valueOf(namaObat.getSelectedItem()).toString();
//                //hasil = service4.getIdObat(nama);
//            } catch (RemoteException ex) {
//                Logger.getLogger(Form_Tambah_Resep.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            try {
//               detail_resep_obat resep = new detail_resep_obat();
//               resep.setid_detail_resep(ID);
//               resep.setid_rekam_medis("rk01");     //perlu DIGANTI !!!!
//               resep.setid_obat(hasil);
//               resep.setqty_detail_resep(Integer.parseInt(String.valueOf(jml.getValue())));
//               
//                if(service3.insertResep(resep)!=null){
//                    
//                    int opsi = JOptionPane.showConfirmDialog(null, "Data Anda berhasil disimpan. Apakah Anda akan menambahkan data lagi?","", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
//                    if(opsi==0){
//                        refresh();
//                    }
////                    else{
////                        Panel_Rekam_Medik_Tambah a = new Panel_Rekam_Medik_Tambah();
////                        a.setVisible(true);
////                        this.dispose();
////                    }
//                }
//                else{
//                    JOptionPane.showMessageDialog(null, "Input Data Eror", "PESAN", JOptionPane.ERROR_MESSAGE);
//                }
//                
//                
//            }
//            catch(RemoteException exception){
//                exception.printStackTrace();
//            }
////            Panel_Rekam_Medik_Tambah a = new Panel_Rekam_Medik_Tambah();
////            a.setVisible(true);
////            this.dispose();
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox boxNamaObat;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jml;
    // End of variables declaration//GEN-END:variables
}
