/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Dokter;

import GUI_Dokter.Form_Tambah_TindakanMedis;
import database.Service.Dokter_Service;
import database.Service.Tindakan_Dokter_Service;
import database.Service.Tindakan_Periksa_Service;
import database.Service.Transaksi_Periksa_Service;
import database.entity.Rekam_Medis;
import database.entity.dokter;
import java.io.File;
import javax.swing.DefaultListModel;
import database.entity.Tindakan_Dokter;
import database.entity.Tindakan_Periksa;
import database.entity.Transaksi_Periksa;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
/**
 *
 * @author Acer
 */
public class Panel_Input_Tindakan_Medis extends javax.swing.JPanel {
      private Dokter_Service service2;
      private Tindakan_Dokter_Service service6;
      private Transaksi_Periksa_Service transaksi;
      private Tindakan_Periksa_Service tinper;
      public Vector listTindakan_Medis= new Vector();
      private String id;
      List<Tindakan_Dokter> td = new ArrayList<Tindakan_Dokter>();
      List<Tindakan_Dokter> list = new ArrayList<Tindakan_Dokter>();
      public GUI_Dokter gui;
      public String a = "";
      
      public String getTanggal(){
        Calendar cal = new GregorianCalendar();
            String tanggal ="0";
            if(cal.get(Calendar.DATE)<0){
                tanggal="0"+cal.get(Calendar.DATE);
            }
            else{
                tanggal=""+cal.get(Calendar.DATE);
            }
            String bulan="0";
            if(cal.get(Calendar.MONTH)<10){
                bulan="0"+(cal.get(Calendar.MONTH)+1);;
            }
            else{
                bulan=""+(cal.get(Calendar.MONTH)+1);
            }
            String tahun= ""+cal.get(Calendar.YEAR);
            tanggal = (tahun+"-"+bulan+"-"+tanggal);
            return tanggal;
    }
      
    public Panel_Input_Tindakan_Medis(GUI_Dokter gui, String id_rekam) {
        initComponents();
        service6 = gui.tds;
        transaksi = gui.tp;
        id = id_rekam;
        tinper = gui.tip;
        this.gui= gui;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(900, 450));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Tindakan Medis yang dilakukan");

        jScrollPane2.setViewportView(jList1);

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Next-32.png"))); // NOI18N
        jButton4.setText("NEXT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel10.setText("3/4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel3)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap(256, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jButton4.setVisible(false);
        int jumlah = 0;
        for (int i = 0; i < list.size(); i++) {
            jumlah = jumlah + list.get(i).getBiaya_Tindakan_Dokter();
        }
        Transaksi_Periksa transaksiperiksa = new Transaksi_Periksa();
        transaksiperiksa.setId_Dokter(gui.d.getid_dokter());
        transaksiperiksa.setId_Pasien(gui.getPasien().getId_Pasien());
        transaksiperiksa.setPPN_Transaksi_Periksa(""+(double)jumlah/10);
        transaksiperiksa.setSubtotal_Transaksi_Periksa(""+jumlah);
        transaksiperiksa.setTotal_Transaksi_Periksa(""+(jumlah+(jumlah/10)));
        transaksiperiksa.setTanggal_Transaksi_Periksa(getTanggal());
        try {
            transaksi.insertTransaksi(transaksiperiksa);
            transaksiperiksa = transaksi.getLastTransaksi();
            for (int i = 0; i < list.size(); i++) {
                Tindakan_Periksa tindakan = new Tindakan_Periksa();
                tindakan.setId_Transaksi_Periksa(transaksiperiksa.getId_Transaksi_Periksa());
                tindakan.setId_Rekam_Medis(""+id);
                tindakan.setId_Tindakan_Dokter(list.get(i).getId_Tindakan_Dokter());
                System.out.println(list.get(i).getTindakan_Dokter());                
                tinper.insertTindakan_Periksa(tindakan);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(Panel_Input_Tindakan_Medis.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Panel_Resep panel = new Panel_Resep(this.gui);
        } catch (RemoteException ex) {
            Logger.getLogger(Panel_Input_Tindakan_Medis.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(Panel_Input_Tindakan_Medis.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan menghapus data ini?");
        if(a==0){
            listTindakan_Medis.remove(jList1.getSelectedIndex());
            list.remove(jList1.getSelectedIndex());
            updateLists(jList1,listTindakan_Medis);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public void updateTindakanMedis(){        
        try{
            list.add(service6.getTindakan_Dokter(a));
            listTindakan_Medis.add(a);
            updateLists(jList1,listTindakan_Medis);
        } catch (RemoteException ex) {
            Logger.getLogger (Panel_Input_Tindakan_Medis.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            td = service6.getAllTindakan_Dokter();
        } catch (RemoteException ex) {
            Logger.getLogger(Panel_Input_Tindakan_Medis.class.getName()).log(Level.SEVERE,null,ex);
        }
        Form_Tambah_TindakanMedis baru = new Form_Tambah_TindakanMedis(this, td);
        baru.setVisible(true);
        this.gui.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void updateLists(JList list, Vector a){
        list.removeAll();
        list.setListData(a);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
