/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Dokter;

import java.util.Calendar;
import java.util.GregorianCalendar;
import Client_Application_Model.TableModel_Antrian;
import database.Service.Pendaftaran_Service;
import database.Service.Pasien_Service;
import database.entity.Antrian;
import database.entity.Pasien;
import database.entity.pendaftaran;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author JESSICA
 */
public class Panel_Rekam_Medik_Awal extends javax.swing.JPanel {
    private TableModel_Antrian tabelModelAntrian = new TableModel_Antrian();
    private Pendaftaran_Service pendaftaranService;
    private Pasien_Service pasienService;
    private Antrian antrian;
    private String action;
    public Pasien pasien;
    private GUI_Dokter gui;    
    
    public Panel_Rekam_Medik_Awal(final GUI_Dokter gui) {
        initComponents();         
        this.gui=gui;
        pendaftaranService = gui.ps;
        pasienService = gui.pas;
        action = "";
        updateMenu.setEnabled(false);      
        refresh();
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                int row = jTable1.getSelectedRow();
                 if(row != -1&&(!action.equals("insert")||(!action.equals("")))){                   
                   antrian = tabelModelAntrian.get(row);
                    try {
                        pasien=pasienService.getPasien(antrian.getId_Pasien());
                        gui.setPasien(pasien);
                        gui.keluhan = antrian.getKeluhan();
                    } catch (RemoteException ex) {
                        Logger.getLogger(Panel_Rekam_Medik_Awal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                   updateMenu.setEnabled(true);
                 }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        updateMenu = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1135, 578));
        setRequestFocusEnabled(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Antrian", "Nama", "Alamat"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        updateMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Next-32.png"))); // NOI18N
        updateMenu.setText("NEXT");
        updateMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMenuActionPerformed(evt);
            }
        });

        jLabel17.setText("*) Pilih salah satu pasien kemudian klik next");

        jButton1.setText("REFRESH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("ANTRIAN ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(493, 493, 493)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(511, 511, 511)
                        .addComponent(updateMenu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(updateMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public String getCalendarNow(){
         Calendar cal = new GregorianCalendar();
         String tanggal ="0";
         if(cal.get(Calendar.DATE)<0){
                tanggal="0"+cal.get(Calendar.DATE);
            }
         else{
                tanggal=""+cal.get(Calendar.DATE);
            }
        String bulan="0";
        if(cal.get(Calendar.MONTH)<10){
            bulan="0"+(cal.get(Calendar.MONTH)+1);;
        }
        else{
            bulan=""+(cal.get(Calendar.MONTH)+1);
        }
        String tahun= ""+cal.get(Calendar.YEAR);
        tanggal = (tahun+"-"+bulan+"-"+tanggal);
        return tanggal;
    }
    
    private void updateMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMenuActionPerformed
        // TODO add your handling code here:
        Panel_History_RekamMedik panel;
        try {
            panel = new Panel_History_RekamMedik(gui);
            gui.updatePanel(panel);
        } catch (RemoteException ex) {
            Logger.getLogger(Panel_Rekam_Medik_Awal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_updateMenuActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_formComponentShown
    private void refresh(){
        try{
            List<pendaftaran> list= new ArrayList<>();
            list = pendaftaranService.getPendaftarans(getCalendarNow());
            if(list.size()>0){
            List<Antrian> a = new ArrayList<Antrian> ();
            for(int i=0;i<list.size();i++ ){
                Antrian aa = new Antrian();
                aa.setNomor(list.get(i).getAntrian());
                Pasien pasien = pasienService.getPasien(list.get(i).getId_Pasien());                
                aa.setKeluhan(list.get(i).getKeluhan());
                aa.setId_Pasien(pasien.getId_Pasien());
                aa.setNama_Pasien(pasien.getNama_Pasien());
                aa.setAlamat(pasien.getAlamat());
                a.add(aa);
            }
             tabelModelAntrian.setData(a);
             jTable1.setModel(tabelModelAntrian);     }
         }catch(RemoteException exception){
             exception.printStackTrace();
         }
    }
    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_formComponentAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton updateMenu;
    // End of variables declaration//GEN-END:variables
}
