/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Apoteker;

import database.entity.obat_kritis;
import GUI_Apoteker.GUI_Apoteker;
import GUI_Apoteker.Panel_Generate_PO;
import java.rmi.RemoteException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import database.entity.Supplier;
import database.Service.Supplier_Service;
/**
 *
 * @author asus
 */
public class Form_ubah_pemesanan_obat extends javax.swing.JFrame {
    obat_kritis ok_baru ;
    Panel_Generate_PO panel_baru;
    GUI_Apoteker gui;
    Supplier_Service supplier2;
    /**
     * Creates new form Form_ubah_pemesanan_obat
     */
    public Form_ubah_pemesanan_obat(GUI_Apoteker gui, Panel_Generate_PO panel) {
        initComponents();
        ok_baru = panel.ok;
        this.gui = gui;
        supplier2 = panel.supplier2;
        panel_baru = panel;
        nomer.setText(""+panel.ok.getNo());
        id_obat.setText(""+panel.ok.getID_OBAT());
        nama_obat.setText(panel.ok.getNAMA_OBAT());
        jumlah_pemesanan.setText(""+panel.ok.getSELISIH());
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomer = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        id_obat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nama_obat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jumlah_pemesanan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        supplierCOmbox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Ubah Pemesanan");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("No :");

        nomer.setEditable(false);
        nomer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomer.setText("11");
        nomer.setEnabled(false);
        nomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomerActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("No_Id_Obat :");

        id_obat.setEditable(false);
        id_obat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id_obat.setText("ob_001");
        id_obat.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nama_Obat :");

        nama_obat.setEditable(false);
        nama_obat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nama_obat.setText("Paracetamol");
        nama_obat.setEnabled(false);
        nama_obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_obatActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Jumlah_Pemesanan :");

        jumlah_pemesanan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jumlah_pemesanan.setText("30");
        jumlah_pemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah_pemesananActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Supplier :");

        supplierCOmbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        supplierCOmbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kimia Farma", "Johnson" }));
        supplierCOmbox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                supplierCOmboxPopupMenuWillBecomeVisible(evt);
            }
        });
        supplierCOmbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierCOmboxActionPerformed(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomer)
                    .addComponent(id_obat)
                    .addComponent(nama_obat)
                    .addComponent(jumlah_pemesanan)
                    .addComponent(supplierCOmbox, 0, 155, Short.MAX_VALUE))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(id_obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(nama_obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jumlah_pemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(supplierCOmbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomerActionPerformed

    private void jumlah_pemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah_pemesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlah_pemesananActionPerformed

    private void supplierCOmboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierCOmboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierCOmboxActionPerformed

    private void nama_obatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_obatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_obatActionPerformed

    private void supplierCOmboxPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_supplierCOmboxPopupMenuWillBecomeVisible
        supplierCOmbox.removeAllItems();
        try {
            List<Supplier> listsup = supplier2.getSupliers();
            for(int i = 0; i<listsup.size(); i++){
                supplierCOmbox.addItem(listsup.get(i).getNama_Supplier().toString());
            }
        } catch (RemoteException ex) {
            Logger.getLogger(Form_ubah_pemesanan_obat.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_supplierCOmboxPopupMenuWillBecomeVisible

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ok_baru.setID_OBAT(id_obat.getText());
        ok_baru.setNAMA_OBAT(nama_obat.getText());
        ok_baru.setNAMA_SUPPLIER(supplierCOmbox.getItemAt(supplierCOmbox.getSelectedIndex()).toString());
        ok_baru.setSELISIH(Integer.parseInt(jumlah_pemesanan.getText()));
        
        panel_baru.updateList(ok_baru);
        try {
            panel_baru.updatetable2();
        } catch (RemoteException ex) {
            Logger.getLogger(Form_ubah_pemesanan_obat.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        gui.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id_obat;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jumlah_pemesanan;
    private javax.swing.JTextField nama_obat;
    private javax.swing.JTextField nomer;
    private javax.swing.JComboBox supplierCOmbox;
    // End of variables declaration//GEN-END:variables
}
