/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Apoteker;

import database.entity.obat_kritis;
import GUI_Apoteker.GUI_Apoteker;
import GUI_Apoteker.Panel_Generate_PO;
import database.Service.Obat_Service;
import java.rmi.RemoteException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import database.entity.Supplier;
import database.Service.Supplier_Service;
import java.awt.Color;
import javax.swing.JOptionPane;
/**
 *
 * @author asus
 */
public class Form_ubah_pemesanan_obat extends javax.swing.JFrame {
    obat_kritis ok_baru ;
    Panel_Generate_PO panel_baru;
    GUI_Apoteker gui;
    Supplier_Service supplier2;
    Obat_Service obs;
    
    /**
     * Creates new form Form_ubah_pemesanan_obat
     */
    public Form_ubah_pemesanan_obat(GUI_Apoteker gui, Panel_Generate_PO panel) {
        initComponents();        
        ok_baru = panel.ok;
        this.gui = gui;
        supplier2 = panel.supplier2;
        panel_baru = panel;
        nomer.setText(""+panel.ok.getNo());
        id_obat.setText(""+panel.ok.getID_OBAT());
        nama_obat.setText(panel.ok.getNAMA_OBAT());
        jumlah_pemesanan.setText(""+panel.ok.getSELISIH());       
        obs = gui.os;
        try {
            initiateComboBox1();            
            supplierCOmbox.setSelectedItem(ok_baru.getNAMA_SUPPLIER().toUpperCase());
        } catch (RemoteException ex) {
            ex.printStackTrace();
            Logger.getLogger(Form_ubah_pemesanan_obat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void initiateComboBox1() throws RemoteException{
        List<Supplier> list = supplier2.getSupliersByNama();        
        for (int i = 0; i < list.size(); i++) {
            supplierCOmbox.addItem(list.get(i).getNama_Supplier().toUpperCase());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomer = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        id_obat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nama_obat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jumlah_pemesanan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        supplierCOmbox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Ubah Pemesanan");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("No :");

        nomer.setEditable(false);
        nomer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomer.setText("11");
        nomer.setEnabled(false);
        nomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomerActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("No_Id_Obat :");

        id_obat.setEditable(false);
        id_obat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id_obat.setText("ob_001");
        id_obat.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nama_Obat :");

        nama_obat.setEditable(false);
        nama_obat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nama_obat.setText("Paracetamol");
        nama_obat.setEnabled(false);
        nama_obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_obatActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Jumlah_Pemesanan :");

        jumlah_pemesanan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jumlah_pemesanan.setText("30");
        jumlah_pemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah_pemesananActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Supplier :");

        supplierCOmbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        supplierCOmbox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                supplierCOmboxPopupMenuWillBecomeVisible(evt);
            }
        });
        supplierCOmbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierCOmboxActionPerformed(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomer)
                            .addComponent(id_obat)
                            .addComponent(nama_obat)
                            .addComponent(jumlah_pemesanan)
                            .addComponent(supplierCOmbox, 0, 155, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(id_obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(nama_obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jumlah_pemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(supplierCOmbox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomerActionPerformed

    private void jumlah_pemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah_pemesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlah_pemesananActionPerformed

    private void nama_obatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_obatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_obatActionPerformed

    
    private boolean CheckNumber(String a){
        char b;
        StringBuffer s;        
        for(int i = 0; i<a.length();i++){
            b = a.charAt(i);                        
            s = new StringBuffer();
            s.append(b);          
            if(!s.toString().equals("1")&&!s.toString().equals("2")&&!s.toString().equals("3")&&!s.toString().equals("4")&&!s.toString().equals("5")&&!s.toString().equals("6")&&!s.toString().equals("7")&&!s.toString().equals("8")&&!s.toString().equals("9")&&!s.toString().equals("0")){               
               return false;
            }            
        }
        return true;
    }
      
      
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean isi1 = false;
        boolean isi2 = false;
        boolean isi3 = false;
        
        if(CheckNumber(jumlah_pemesanan.getText())&&!jumlah_pemesanan.getText().equals("")){
            isi1=true;            
        }           
        if(!supplierCOmbox.getItemAt(supplierCOmbox.getSelectedIndex()).toString().equals("Kimia Farma")){
            isi2=true;
        }
        if(isi1){
            if(panel_baru.ok.getSELISIH()<=Integer.parseInt(jumlah_pemesanan.getText())){
                isi3= true;
            }                
        }
        
        if(isi1&&isi2&&isi3){
            ok_baru.setID_OBAT(id_obat.getText());
            ok_baru.setNAMA_OBAT(nama_obat.getText());
            ok_baru.setNAMA_SUPPLIER(ok_baru.getNAMA_SUPPLIER());
            ok_baru.setSELISIH(Integer.parseInt(jumlah_pemesanan.getText()));
            try {
                ok_baru.setHARGA(obs.getObat(id_obat.getText()).getharga_obat());
                ok_baru.setTOTAL(ok_baru.getHarga()*ok_baru.getSELISIH());
            } catch (RemoteException ex) {
                Logger.getLogger(Form_ubah_pemesanan_obat.class.getName()).log(Level.SEVERE, null, ex);
            }
            panel_baru.updateList(ok_baru);
            try {
                panel_baru.updatetable2();
            } catch (RemoteException ex) {
                Logger.getLogger(Form_ubah_pemesanan_obat.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
            gui.setVisible(true);
        }
        else{
            if(!isi1||!isi2){
                if(!isi1){
                    jumlah_pemesanan.setBackground(Color.red);                                
                }
                if(!isi2){
                    supplierCOmbox.setBackground(Color.red);
                }
                JOptionPane.showMessageDialog(null, "Ada kesalahan pada field isian Anda. Mohon perbaiki field yang berwarna merah untuk melanjutkan","ERROR",JOptionPane.ERROR_MESSAGE);
            }
            if(!isi3){
                JOptionPane.showMessageDialog(null, "Mohon mengisi jumlah pemesanan minimal sejumlah yang disarankan yaitu " +panel_baru.ok.getSELISIH(),"ERROR",JOptionPane.ERROR_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void supplierCOmboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierCOmboxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_supplierCOmboxActionPerformed

    private void supplierCOmboxPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_supplierCOmboxPopupMenuWillBecomeVisible
        supplierCOmbox.removeAllItems();
        try {
            initiateComboBox1();
        } catch (RemoteException ex) {
            Logger.getLogger(Form_ubah_pemesanan_obat.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_supplierCOmboxPopupMenuWillBecomeVisible


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id_obat;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jumlah_pemesanan;
    private javax.swing.JTextField nama_obat;
    private javax.swing.JTextField nomer;
    private javax.swing.JComboBox supplierCOmbox;
    // End of variables declaration//GEN-END:variables
}
