/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Apoteker;

import database.Service.Obat_Service;
import database.Service.Supplier_Service;
import database.entity.Supplier;
import database.entity.obat;
import java.awt.Color;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Form_Data_Supplier_Ubah extends javax.swing.JFrame {
    GUI_Apoteker gui;
    public Supplier supplier;
    Supplier_Service supplierservice;
    Registry registry;
    /**
     * Creates new form TAMBAH
     */
    public Form_Data_Supplier_Ubah(GUI_Apoteker gui, Supplier s) {
        initComponents();
        supplierservice = gui.ss;
        supplier = s;
        this.gui = gui;
        nama1.setText(supplier.getId_Supplier());
        NAMA.setText(supplier.getNama_Supplier());
        ALAMAT.setText(supplier.getAlamat_Supplier());
        KOTA.setText(supplier.getKota_Supplier());
        KODEPAJAK.setText(supplier.getKode_Pajak_Supplier());
        TELEPON.setText(supplier.getTelepon_Supplier());
        NPWP.setText(supplier.getNPWP_Supplier());        
    }
    
    
    public Form_Data_Supplier_Ubah() throws RemoteException, NotBoundException {
        initComponents();
        registry = LocateRegistry.getRegistry("0.0.0.0", 9750);
        supplierservice = (Supplier_Service) registry.lookup("service12");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        NAMA = new javax.swing.JTextField();
        KOTA = new javax.swing.JTextField();
        TELEPON = new javax.swing.JTextField();
        NPWP = new javax.swing.JTextField();
        JENISPAJAK = new javax.swing.JComboBox();
        KODEPAJAK = new javax.swing.JTextField();
        CANCEL = new javax.swing.JButton();
        OK = new javax.swing.JButton();
        ALAMAT = new java.awt.TextArea();
        jLabel10 = new javax.swing.JLabel();
        nama1 = new javax.swing.JTextField();
        BACK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel1.setText("UPDATE DATA SUPPLIER");

        jLabel3.setText("NAMA SUPPLIER ");

        jLabel4.setText("ALAMAT");

        jLabel5.setText("KOTA");

        jLabel6.setText("TELEPON");

        jLabel7.setText("NPWP");

        jLabel8.setText("JENIS PAJAK");

        jLabel9.setText("KODE PAJAK");

        JENISPAJAK.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilihan", " " }));

        KODEPAJAK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KODEPAJAKActionPerformed(evt);
            }
        });

        CANCEL.setText("CANCEL");
        CANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELActionPerformed(evt);
            }
        });

        OK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Save-32.png"))); // NOI18N
        OK.setText("SIMPAN");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        jLabel10.setText("ID SUPPLIER ");

        nama1.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(OK)
                        .addGap(193, 193, 193)
                        .addComponent(CANCEL))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(JENISPAJAK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(KOTA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                .addComponent(TELEPON, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NPWP, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(KODEPAJAK, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(ALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(nama1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NAMA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)))
                        .addGap(0, 25, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(nama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(KOTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(TELEPON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(NPWP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(JENISPAJAK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(KODEPAJAK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(OK))
                    .addComponent(CANCEL, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(17, 17, 17))
        );

        BACK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Previous-32.png"))); // NOI18N
        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(107, 107, 107)
                .addComponent(BACK, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BACK)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELActionPerformed
        Form_data_suplier o1;
        try {
            o1 = new Form_data_suplier(gui);
            gui.updatePanel(o1);
                this.dispose();
        } catch (RemoteException ex) {
            Logger.getLogger(Form_Data_Supplier_Tambah.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(Form_Data_Supplier_Tambah.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CANCELActionPerformed

    public void setNama (String a){
        NAMA.setText(a);
    }
    
    public void setAlamat (String a){
        ALAMAT.setText(a);
    }
    
    public void setKota (String a){
        KOTA.setText(a);
    }
    
    public void setTelp (String a){
        TELEPON.setText(a);
    }
    
    
    public void setNPWP (String a){
        NPWP.setText(a);
    }
    
    public void setJenisPajak (String i){
        JENISPAJAK.addItem(i);
        JENISPAJAK.setSelectedIndex(JENISPAJAK.getItemCount()-1);
    }
    
    public void setKodePajak (String a){
        KODEPAJAK.setText(a);
    }
    
     public boolean cekNamaSupplierSudahAda(){
        boolean ada = false;
        try {
            List<Supplier> list = supplierservice.getSupliers();
            for (int i = 0; i < list.size(); i++) {
                if(list.get(i).getNama_Supplier().equalsIgnoreCase(NAMA.getText())){
                    ada = true;
                }
            }
        } catch (RemoteException ex) {
            Logger.getLogger(Form_Data_Supplier_Tambah.class.getName()).log(Level.SEVERE, null, ex);
        }
        return ada;
    }
    
    public boolean UbahSupplier(){
        boolean isi1 = false;
        boolean isi2 = false;
        boolean isi3 = false;
        boolean isi4 = false;
        boolean isi5 = false;
        boolean isi6 = false;
        boolean isi7 = false;
        boolean sukses = false;
        if(!NAMA.getText().equals("")){
            isi1 = true;
            System.out.println("isi1");
        }
        if(!ALAMAT.getText().equals("")){
            isi2 = true;
            System.out.println("isi2");
        }
        if(!KOTA.getText().equals("")){
            isi3 = true;
            System.out.println("isi3");
        }
        if(!TELEPON.getText().equals("")){
            isi4 = true;
            System.out.println("isi4");
        }
        if(!NPWP.getText().equals("")){
            isi5 = true;
            System.out.println("isi5");
        }
        if(!JENISPAJAK.getItemAt(JENISPAJAK.getSelectedIndex()).toString().equals("")) {
            isi6 = true;
            System.out.println("isi6");
        }
        if(!KODEPAJAK.getText().equals("")){
            isi7 = true;
            System.out.println("isi7");
        }
        boolean nama = false;
        if(!supplier.getNama_Supplier().equals(NAMA.getText())){ 
            nama = cekNamaSupplierSudahAda();
            System.out.println(NAMA.getText());
        }
        if(!nama&&isi1&&isi2&&isi3&&isi4&&isi5&&isi6&&isi7)    {
            String N = NAMA.getText();
            String A = ALAMAT.getText();
            String K = KOTA.getText();
            String T = TELEPON.getText();
            String NP = NPWP.getText();
            String JP = JENISPAJAK.getItemAt(JENISPAJAK.getSelectedIndex()).toString();
            String KP = KODEPAJAK.getText();                                         
               supplier.setNama_Supplier(N);
               supplier.setAlamat_Supplier(A);
               supplier.setKota_Supplier(K);
               supplier.setTelepon_Supplier(T);
               supplier.setNPWP_Supplier(NP);
               supplier.setJenis_pajak_Supplier(JP);
               supplier.setKode_Pajak_Supplier(KP);
               try {                    
                    supplierservice.updateSupplier(supplier);
                    sukses = true;
                    JOptionPane.showConfirmDialog(null, "Data Anda berhasil disimpan. Apakah Anda ingin mengubah data lagi?","", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                    if(gui!=null){
                    gui.updatePanel(new Form_data_suplier (gui));
                    this.dispose();}
                } catch (NotBoundException ex) {
                    Logger.getLogger(Form_Data_Supplier_Ubah.class.getName()).log(Level.SEVERE, null, ex);
                }
                catch(RemoteException exception){
                    exception.printStackTrace();
                }       
        }
        else{
            if(!isi1){
                NAMA.setBackground(Color.red);
            }
            if(!isi2){
                ALAMAT.setBackground(Color.red);
            }
            if(!isi3){
                KOTA.setBackground(Color.red);
            }

            if(!isi4){
                TELEPON.setBackground(Color.red);
            }
            
             if(!isi5){
                NPWP.setBackground(Color.red);
            }
            if(!isi6){
                JENISPAJAK.setBackground(Color.red);
            }

            if(!isi7){
                KODEPAJAK.setBackground(Color.red);
            }
            JOptionPane.showMessageDialog(null, "Ada kesalahan pada kolom isian Anda. Mohon memperbaiki field yang berwarna merah untuk melanjutkan.", "ERROR", JOptionPane.ERROR_MESSAGE);
    
        }
        return sukses;
    }
    
    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_OKActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        // TODO add your handling code here:
        Form_data_suplier o1;
        try {
            o1 = new Form_data_suplier(gui);
            gui.updatePanel(o1);
                this.dispose();
        } catch (RemoteException ex) {
            Logger.getLogger(Form_Data_Supplier_Tambah.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(Form_Data_Supplier_Tambah.class.getName()).log(Level.SEVERE, null, ex);
        }
             
    }//GEN-LAST:event_BACKActionPerformed

    private void KODEPAJAKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KODEPAJAKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KODEPAJAKActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea ALAMAT;
    private javax.swing.JButton BACK;
    private javax.swing.JButton CANCEL;
    private javax.swing.JComboBox JENISPAJAK;
    private javax.swing.JTextField KODEPAJAK;
    private javax.swing.JTextField KOTA;
    private javax.swing.JTextField NAMA;
    private javax.swing.JTextField NPWP;
    private javax.swing.JButton OK;
    private javax.swing.JTextField TELEPON;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nama1;
    // End of variables declaration//GEN-END:variables
}
