/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//yg baru
package GUI_Apoteker;
import Client_Application_Model.TableModel_Generate_PO;
import GUI_Apoteker.Form_ubah_pemesanan_obat;
import database.Service.List_PO_Service;
import database.entity.obat_kritis;
import database.entity.Supplier;
import database.entity.detil_pesan_obat;
import database.entity.Pemesanan_Obat;
import database.Service.Obat_Service;
import database.Service.Supplier_Service;
import database.Service.Pemesanan_Obat_Service;
import java.rmi.RemoteException;
import java.util.List;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author asus
 */
public class Panel_Generate_PO extends javax.swing.JPanel {
    TableModel_Generate_PO table = new TableModel_Generate_PO();
    Obat_Service obs;
    obat_kritis ok;
    Pemesanan_Obat_Service pos;
    List_PO_Service lpos;
    Supplier_Service supplier2;
    GUI_Apoteker gui;
    List<obat_kritis> listob;
    List<Pemesanan_Obat> listPO= new ArrayList<Pemesanan_Obat>();
    
    int index;
    
    /**
     * Creates new form Panel_Generate_PO
     */
    public Panel_Generate_PO(GUI_Apoteker gui) {
        initComponents();
        obs = gui.os;
        supplier2 = gui.ss;
        pos = gui.pos;
        lpos = gui.listPO;
        this.gui = gui;
        UBAH.setEnabled(false);
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                int row = jTable1.getSelectedRow();
                 if(row != -1){                   
                   UBAH.setEnabled(true);
                   ok = table.get(row);
                   index = row;
                 }
            }
        });
    }

    public void updateList(obat_kritis ob){
        listob.set(index, ob);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        UBAH = new javax.swing.JButton();
        generatePO = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1170, 530));
        setPreferredSize(new java.awt.Dimension(1170, 530));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "no", "id_obat", "nama_obat", "jumlah_harus_dipesan", "supplier"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Data Pemesanan Obat");

        UBAH.setText("ubah");
        UBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UBAHActionPerformed(evt);
            }
        });

        generatePO.setText("SIMPAN DAN GENERATE PO");
        generatePO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatePOActionPerformed(evt);
            }
        });

        jLabel2.setText("TOTAL HARGA YANG HARUS DIBAYAR  :");

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(482, 482, 482)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(UBAH, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(474, 474, 474)
                .addComponent(generatePO, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(500, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(UBAH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(generatePO, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UBAHActionPerformed
        Form_ubah_pemesanan_obat ub= new Form_ubah_pemesanan_obat(this.gui,this);
        gui.setVisible(false);        
        ub.setVisible(true);
        UBAH.setEnabled(false);
    }//GEN-LAST:event_UBAHActionPerformed

    public String getTanggal(){
       Calendar cal = new GregorianCalendar();
            String tanggal ="0";
            if(cal.get(Calendar.DATE)<0){
                tanggal="0"+cal.get(Calendar.DATE);
            }
            else{
                tanggal=""+cal.get(Calendar.DATE);
            }
            String bulan="0";
            if(cal.get(Calendar.MONTH)<10){
                bulan="0"+(cal.get(Calendar.MONTH)+1);;
            }
            else{
                bulan=""+(cal.get(Calendar.MONTH)+1);
            }
            String tahun= ""+cal.get(Calendar.YEAR);
            tanggal = (tahun+"-"+bulan+"-"+tanggal);
        return tanggal;
    }
    
    private void generatePOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatePOActionPerformed
        int size = 0;
        System.out.println("size list ob "+listob.size());
        List<Pemesanan_Obat> listPo = null;
        try {
            listPo = pos.getPO();
        } catch (RemoteException ex) {
            Logger.getLogger(Panel_Generate_PO.class.getName()).log(Level.SEVERE, null, ex);
        }
        size = listPo.size();        
        System.out.println("ini size awal tabel PO:"+size);
        if(listob.size()>0){
            Pemesanan_Obat po = new Pemesanan_Obat();
            po.setId_Pemesnan_obat("PO"+(size+1));
            System.out.println("ini hasil generate id po :"+po.getId_Pemesanan_obat());
            try {
                 po.setId_supplier(supplier2.getId_Supplier(listob.get(0).getNAMA_SUPPLIER()).getId_Supplier());
            } catch (RemoteException ex) {
                Logger.getLogger(Panel_Generate_PO.class.getName()).log(Level.SEVERE, null, ex);
            }
            po.setTgl_Pemesanan(getTanggal());           
            po.setList(new ArrayList<detil_pesan_obat>());
            try {
                pos.insertPemesananObat(po);
            } catch (RemoteException ex) {
                Logger.getLogger(Panel_Generate_PO.class.getName()).log(Level.SEVERE, null, ex);
            }
            size = size+1;
            listPO.add(po);           
            int index = 0;
            
            for(int i = 0; i<listob.size(); i++){
                boolean ada = false;
                for(int j = 0; j<listPO.size();j++){
                    try {
                        if(supplier2.getSupplier(listPO.get(j).getId_supplier()).getNama_Supplier().equals(listob.get(i).getNAMA_SUPPLIER())){      
                            System.out.println("ini suppliernya sama, id_suppliernya "+listob.get(i).getNAMA_SUPPLIER());
                            ada  = true;
                            index = j;
                        }
                    } catch (RemoteException ex) {
                        Logger.getLogger(Panel_Generate_PO.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if(ada){
                    try {
                        detil_pesan_obat detail = new detil_pesan_obat();
                        detail.setId_Pemesanan_obat(listPO.get(index).getId_Pemesanan_obat());
                        System.out.println("Jadi, obat "+ listob.get(i).getID_OBAT() + " mempunyai id PO" + detail.getId_Pemesanan_obat());
                        detail.setId_obat(listob.get(i).getID_OBAT());
                        detail.setJumlah_pesan(listob.get(i).getSELISIH());
                        detail.setStatus(0);
                        List<detil_pesan_obat>list = listPO.get(index).getList();
                        list.add(detail);
                        lpos.insertListPO(detail); 
                        System.out.println("lalu dia insertkan detail list po'nya");
                        listPO.get(index).setList(list);
                    } catch (RemoteException ex) {
                        Logger.getLogger(Panel_Generate_PO.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else{
                    po = new Pemesanan_Obat();
                    po.setId_Pemesnan_obat("PO"+(size+1));
                    System.out.println("obat : "+listob.get(i).getNAMA_OBAT()+" Suppliernya adalah : "+listob.get(i).getNAMA_SUPPLIER()+" . Ini berarti supplier obat ini tidak ada yang sama. ID POnya digenerate lagi, " + po.getId_Pemesanan_obat());
                    try {
                        po.setId_supplier(supplier2.getId_Supplier(listob.get(i).getNAMA_SUPPLIER()).getId_Supplier());
                    } catch (RemoteException ex) {
                        Logger.getLogger(Panel_Generate_PO.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    po.setList(new ArrayList<detil_pesan_obat>());
                    po.setTgl_Pemesanan(getTanggal());
                    listPO.add(po);
                    try {
                        pos.insertPemesananObat(po);
                    } catch (RemoteException ex) {
                        Logger.getLogger(Panel_Generate_PO.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    detil_pesan_obat detail = new detil_pesan_obat();
                    detail.setId_Pemesanan_obat(listPO.get(listPO.size()-1).getId_Pemesanan_obat());
                    System.out.println("Detailnya dimasukkan dengan id PO: "+ detail.getId_Pemesanan_obat());
                    detail.setId_obat(listob.get(i).getID_OBAT());
                    detail.setJumlah_pesan(listob.get(i).getSELISIH());
                    detail.setStatus(0);
                    List<detil_pesan_obat>list = listPO.get(listPO.size()-1).getList();
                    list.add(detail);
                    listPO.get(listPO.size()-1).setList(list); 
                }
            }
            for (int i = 0; i < listPO.size(); i++) {
                try {
                    listPO.get(i).setNama_supllier(supplier2.getSupplier(listPO.get(i).getId_supplier()).getNama_Supplier());                    
                } catch (RemoteException ex) {
                    Logger.getLogger(Panel_Generate_PO.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            Panel_List_PO panel  = new Panel_List_PO (gui,listPO);
            panel.updateTabel();
            gui.updatePanel(panel);
            
            
            System.out.println("ada "+listPO.size()+" supplier");
        }
    }//GEN-LAST:event_generatePOActionPerformed
    
    public  void updatetable() throws RemoteException{
        listob = obs.getObatKritis();
        for (int i = 0; i < listob.size(); i++) {
            listob.get(i).setNo(i+1);
            listob.get(i).setHARGA(obs.getObat(listob.get(i).getID_OBAT()).getharga_obat());
            listob.get(i).setTOTAL(listob.get(i).getHarga()*listob.get(i).getSELISIH());
        }
        System.out.println(listob.size());
        table.setData(listob);
        jTable1.setModel(table);        
        int harga = 0;
        for (int i = 0; i < listob.size(); i++) {
            harga =  harga + listob.get(i).getTOTAL();
        }
        jLabel3.setText("Rp "+harga);
    }
    
    public  void updatetable2() throws RemoteException{
        table.setData(listob);
        jTable1.setModel(table);   
        int harga = 0;
        for (int i = 0; i < listob.size(); i++) {
            harga =  harga + listob.get(i).getTOTAL();
        }
        jLabel3.setText("Rp "+harga);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UBAH;
    private javax.swing.JButton generatePO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
