/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Apoteker;

import GUI_Dokter.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import Client_Application_Model.TableModel_Antrian;
import database.Service.Pendaftaran_Service;
import database.Service.Pasien_Service;
import database.Service.RekamMedik_Service;
import database.entity.Rekam_Medis;
import database.entity.Antrian;
import database.entity.Pasien;
import database.entity.pendaftaran;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author JESSICA
 */
public class Panel_Antrian extends javax.swing.JPanel {
    private TableModel_Antrian tabelModelAntrian = new TableModel_Antrian();
    private Pendaftaran_Service pendaftaranService;
    private Pasien_Service pasienService;
    private RekamMedik_Service rekamService;
    private Antrian antrian;
    private Rekam_Medis rekamMedis; 
    public Pasien pasien;
    private GUI_Apoteker gui;    
    
    public Panel_Antrian(final GUI_Apoteker gui) {
        initComponents();         
        this.gui=gui;
        pendaftaranService = gui.pds;
        pasienService = gui.pas;
        rekamService = gui.rm;
        updateMenu.setEnabled(false);      
        refresh();
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                int row = jTable1.getSelectedRow();
                   antrian = tabelModelAntrian.get(row);
                    try {
                        pasien=pasienService.getPasien(antrian.getId_Pasien());
                        gui.setPasien(pasien);
                        System.out.println(pasien.getId_Pasien());
                        rekamMedis = rekamService.getLastRekamMedik(pasien.getId_Pasien());
                        System.out.println(rekamMedis.getId_Rekam_Medis());
                    } catch (RemoteException ex) {
                        Logger.getLogger(Panel_Rekam_Medik_Awal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                   updateMenu.setEnabled(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        updateMenu = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1183, 570));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Antrian", "Nama", "Alamat"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        updateMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Next-32.png"))); // NOI18N
        updateMenu.setText("NEXT");
        updateMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMenuActionPerformed(evt);
            }
        });

        jLabel17.setText("*) Pilih salah satu pasien kemudian klik next");

        jButton1.setText("REFRESH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(0, 946, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(updateMenu)
                        .addGap(506, 506, 506))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public String getCalendarNow(){
         Calendar cal = new GregorianCalendar();
         String tanggal ="0";
         if(cal.get(Calendar.DATE)<0){
                tanggal="0"+cal.get(Calendar.DATE);
            }
         else{
                tanggal=""+cal.get(Calendar.DATE);
            }
        String bulan="0";
        if(cal.get(Calendar.MONTH)<10){
            bulan="0"+(cal.get(Calendar.MONTH)+1);;
        }
        else{
            bulan=""+(cal.get(Calendar.MONTH)+1);
        }
        String tahun= ""+cal.get(Calendar.YEAR);
        tanggal = (tahun+"-"+bulan+"-"+tanggal);
        return tanggal;
    }
    
    private void updateMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMenuActionPerformed
        // TODO add your handling code here:
        Panel_DetailResep panel;
            panel = new Panel_DetailResep(rekamMedis.getId_Rekam_Medis().toString(),gui);
            gui.updatePanel(panel);
    }//GEN-LAST:event_updateMenuActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_formComponentShown
    private void refresh(){
        try{
            List<pendaftaran> list= new ArrayList<>();
            list = pendaftaranService.getPendaftarans(getCalendarNow());
            if(list.size()>0){
            List<Antrian> a = new ArrayList<Antrian> ();
            for(int i=0;i<list.size();i++ ){
                Antrian aa = new Antrian();
                aa.setNomor(list.get(i).getAntrian());
                Pasien pasien = pasienService.getPasien(list.get(i).getId_Pasien());                
                aa.setKeluhan(list.get(i).getKeluhan());
                aa.setId_Pasien(pasien.getId_Pasien());
                aa.setNama_Pasien(pasien.getNama_Pasien());
                aa.setAlamat(pasien.getAlamat());
                a.add(aa);
            }
             tabelModelAntrian.setData(a);
             jTable1.setModel(tabelModelAntrian);     }
         }catch(RemoteException exception){
             exception.printStackTrace();
         }
    }
    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_formComponentAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton updateMenu;
    // End of variables declaration//GEN-END:variables
}
